### ISSUE TITLE
Icon library preview

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_icons.dart#18]
Would it be possible to generate a doc page that would list all available icons together with a preview of the icon? Bonus points for listing icon names to be able to search. ;)

**Comment by Jupi007** [comment]
It is a really good idea!
I'll take a look at this :)

**Comment by Jupi007** [comment]
@jpnurmi Please take a look at: https://github.com/ubuntu/yaru_icons.dart/blob/master/doc/icon_list.md :)

**Comment by Feichtmeier** [comment]
Awesome stuff!
So this preview is now visible when you autocomplete in vscode?

**Comment by Jupi007** [comment]
> Awesome stuff! So this preview is now visible when you autocomplete in vscode?

Nope, sorry. I just generated a Markdown file.
I didn't know this was possible btw

**Comment by jpnurmi** [comment]
Yay, very nice! Thank you!

**Comment by Feichtmeier** [comment]
> > Awesome stuff! So this preview is now visible when you autocomplete in vscode?
> 
> Nope, sorry. I just generated a Markdown file.
> I didn't know this was possible btw

Okay I think I know how to do this.. Maybe I can make a contribution here

**Comment by jpnurmi** [comment]
Material and Cupertino icons seem to have a special treatment in Dart-Code: :unamused:
https://github.com/Dart-Code/Dart-Code/blob/master/src/shared/utils/dartdocs.ts#L40-L56

The icons are shipped in `~/.vscode/extensions/dart-code.dart-code-x.y.z/media/doc-icons/material`

**Comment by Jupi007** [comment]
> Material and Cupertino icons seem to have a special treatment in Dart-Code: unamused https://github.com/Dart-Code/Dart-Code/blob/master/src/shared/utils/dartdocs.ts#L40-L56
> 
> The icons are shipped in `~/.vscode/extensions/dart-code.dart-code-x.y.z/media/doc-icons/material`

Thanks for the investigation.
I was trying to understand how html icons blocks was working in dart code block, but this wasn't possible 😅

@Feichtmeier Are you sure? If you know a way to display an image it could be awesome. But as said @jpnurmi it is sadly impossible.

**Comment by jpnurmi** [comment]
Disclaimer: I have never developed VS Code plugins. :smile: Perhaps it's possible with a custom extension?

**Comment by Jupi007** [comment]
Surly yes I think, but isn't create a new extension just to preview those icons inside VS Code a bit overkill 😅

**Comment by jpnurmi** [comment]
How about remote .png files? (.svg doesn't seem to work)
```
  /// ![computer](https://github.com/ubuntu/yaru/raw/master/icons/Yaru/32x32/devices/computer.png)
  static const IconData computer = YaruIconsData(0xf136);
```

![image](https://user-images.githubusercontent.com/140617/140408813-b0628b59-17fb-4e6f-af08-426a4d28664a.png)

**Comment by Jupi007** [comment]
Using .png file could indeed works.
But it will require to adapt the tool I use to generate the font and the icon class.

Can you open a new issue for that, please @jpnurmi 
I think it could be a nice feature, so we need a good place for the discussion :)

**Comment by Feichtmeier** [comment]
> Material and Cupertino icons seem to have a special treatment in Dart-Code: :unamused:
> https://github.com/Dart-Code/Dart-Code/blob/master/src/shared/utils/dartdocs.ts#L40-L56
> 
> The icons are shipped in `~/.vscode/extensions/dart-code.dart-code-x.y.z/media/doc-icons/material`

Ohhhh.hm Maybe we could ask the dart code maintainer then.

**Comment by jpnurmi** [comment]
A generic solution for extra icon packages would be great! For example, a setting for the Dart-Code extension. There are lots of Flutter icon packages out there.

**Comment by Feichtmeier** [comment]
@DanTup hello there :wave: 

Do you think it would be possible to include a yaru icons preview inside dartcode?
It is the default icon set for Ubuntu desktop flutter applications :smiley_cat:

**Comment by DanTup** [comment]
Hey!

I don't think the current solution for icons in Dart-Code is ideal. The current icons shipped in Dart-Code are lifted from https://github.com/flutter/tools_metadata/tree/master/resources/icons and shipped inside the extension. This makes the extension quite large (probably 99% of the extension is icon files) and does not version correctly (all users get the same set of icons regardless of their actual SDK version, so when icons are tweaked/updated, they see the wrong ones). This implementation is also very VS Code-specific, and doesn't work for any other editors using the LSP language server. I don't think this way will scale well for previews for third-party packages.

I think a better way would be for there to be some general way for packages to include icons. Perhaps similar to the web example shown above - but where the path can be relative in some way so the icons can come from the package rather than being pulled over the web - or maybe some additional metadata in the package (which would have the advantage of supporting them in the gutter or similar too).

There's some slightly related discussion in https://github.com/dart-lang/sdk/issues/44682 (which was about colours which is slightly simpler, but touches on icons too), although the colour work is mostly done so that will be closed soon so I've filed https://github.com/dart-lang/sdk/issues/47667 about something more generic - feel free to add 👍 s/comments there.

(In the short-term, I think adding image URLs as in the screenshot above might be the simplest solution to get some previews, albeit not in the gutter).
